modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"
showAsResourcePack=false
displayURL="https://github.com/JnCrMx/MinecraftDiscordLobbies"
issueTrackerURL="https://github.com/JnCrMx/MinecraftDiscordLobbies/issues"

[[mods]]
modId="discordlobbies"
version="${version}"
displayName="Discord Lobbies"
authors="JCM"
description="A mod that enables multiplayer over Discord lobbies and its networking layer."

[[dependencies.discordlobbies]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.discordlobbies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
